---
abstract: Mojo::Twist
author:
  - 'sattellite <sattellite@ya.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-Twist
no_index:
  directory:
    - t
    - inc
requires:
  Class::Load: 0
  Mojolicious: 4.63
  Test::Spec: 0
  Time::Piece: 0
version: 0.1
